name: "[CI]master push"
on:
  push:
    paths-ignore:
      - '.github/**'
    branches:
      - master

  workflow_dispatch:

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.job1.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v2
      - name: calculate current date
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
          echo "::set-env name=TIME::$(date +'%Y%m%d.%H%M%S')"
      - name: calculate_version
        id: job1
        run: |
          echo "::set-output name=VERSION::$(cat src/VERSION | cut -c 2-).${{ env.TIME }}"

  docker:
    if: github.repository_owner == 'spaceone-dev'
    needs: versioning
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ needs.versioning.outputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: get service name
        run: |
          echo "::set-env name=SERVICE::$(echo ${{ github.repository }} | cut -c 14-)"

      - name: build "build image" for caching
        run: |
          mv Dockerfile Dockerfile2
          mv build_Dockerfile Dockerfile
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker pull pyengine/build:console
          \docker build -t pyengine/build:console -c 2048 --cache-from pyengine/build:console .
          docker push pyengine/build:console
          rm Dockerfile
          mv Dockerfile2 Dockerfile
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: upload the docker image on ECR
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ secrets.AWS_ROOT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com
          \docker build -t ${{ secrets.AWS_ROOT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/spaceone/console:latest -c 2048 .
          docker tag ${{ secrets.AWS_ROOT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/spaceone/console:latest ${{ secrets.AWS_ROOT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/spaceone/console:${{ env.VERSION }}
          docker push ${{ secrets.AWS_ROOT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/spaceone/console:latest
          docker push ${{ secrets.AWS_ROOT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/spaceone/console:${{ env.VERSION }}
        # - name: build "build image" for caching
        # uses: docker/build-push-action@v1
        # with:
        #   path: .
        #   dockerfile: ./build_Dockerfile
        #   repository: pyengine/build
        #   username: ${{ secrets.DOCKER_USERNAME }}
        #   password: ${{ secrets.DOCKER_PASSWORD }}
        #   tags: console
        #   cache_froms: pyengine/build:console

      # - name: Upload the docker image on ECR
      #   uses: kciter/aws-ecr-action@v1
      #   with:
      #     access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     account_id: ${{ secrets.AWS_ROOT_ID }}
      #     repo: spaceone/${{ env.SERVICE }}
      #     region: ap-northeast-2
      #     tags: latest,${{ env.VERSION }}
      #     create_repo: false
          
      - name: Slack
        if: always()
        uses: 8398a7/action-slack@v3.2.0
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          author_name: Github Action Slack
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}