# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - master

jobs:        
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: version check
        id: check
        uses: EndBug/version-check@v1
      - uses: actions/checkout@v2
        if: steps.check.outputs.changed == 'true'
      - uses: actions/setup-node@v1
        if: steps.check.outputs.changed == 'true'
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Checkout submodules
        if: steps.check.outputs.changed == 'true'
        uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      - run: npm ci
        if: steps.check.outputs.changed == 'true'
      - name: build
        if: steps.check.outputs.changed == 'true'
        run: npm run build:lib
      - name: publish
        if: steps.check.outputs.changed == 'true'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

