name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/   
          
      - name: Setup GIT
      - run: |
          git config user.email "github-actions@github.com"
          git config user.name "github-actions"
          git pull
          
      - name: Bump version
      - run: |
          npm version prerelease --no-git-tag-version --preid=dev 
          git add .
          git commit -m "[CI/CD] Update package version"
          git push
      - run: npm install
      - run: npm run build
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
